---
# tasks file for Debian9-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist Ubuntu 18.04. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - not ansible_distribution == "Debian"
      - not ansible_distribution_release == "stretch"
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include: prelim.yml
  become: true
  tags:
      - prelim_tasks
      - always

- include: section1.yml
  become: true
  when: debian9cis_section_1
  tags: section1

- include: section2.yml
  become: true
  when: debian9cis_section_2
  tags: section2

- include: section3.yml
  become: true
  when: debian9cis_section_3
  tags: section3

- include: section4.yml
  become: true
  when: debian9cis_section_4
  tags: section4