---
# handlers file for debian9-CIS
- name: update_grub
  become: true
  command: update-grub

- name: systemd restart tmp.mount
  become: true
  systemd:
      name: tmp.mount
      daemon_reload: true
      enabled: true
      masked: false
      state: reloaded
  when:
    - ansible_virtualization_type != "docker"
    - not debian9cis_chroot
  ignore_errors: "{{ debian9cis_ignore_remount_errors }}"

- name: systemd restart var-tmp.mount
  become: true
  systemd:
      name: var-tmp.mount
      daemon_reload: true
      enabled: true
      masked: false
      state: reloaded
  when:
    - not debian9cis_chroot
  ignore_errors: "{{ debian9cis_ignore_remount_errors }}"

- name: persist iptables
  shell: iptables-save > /etc/iptables/rules.v4

- name: persist ip6tables
  shell: ip6tables-save > /etc/iptables/rules.v6

- name: restart auditd
  systemd:
    name: auditd
    state: restarted
    enabled: true
  when:
    - not debian9cis_skip_for_travis
    - not debian9cis_chroot

- name: reload rsyslogd
  command: pkill -HUP rsyslogd

- name: reload syslog-ng
  systemd:
    name: syslog-ng
    state: reloaded
    enabled: true
    masked: false

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
    enabled: true
    masked: false

- name: apply SPS changes
  command: usermod